#version 460
#extension GL_EXT_ray_tracing : require
layout(set=0,binding=0) uniform accelerationStructureEXT scene;
layout(location=0) rayPayloadEXT vec4 payload;
layout(location=1) rayPayloadEXT vec4 unusedPayload;
layout(location=2) callableDataEXT float callable;
layout(location=3) callableDataEXT float unusedCallable;
void main() {
traceRayEXT(scene,0u,255u,0u,0u,0u,vec3(0.0),0.0,vec3(0.0,0.0,1.0),1.0,0);
executeCallableEXT(0u,2);
}
