#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>
#if __METAL_VERSION__ >= 230
#include <metal_raytracing>
using namespace metal::raytracing;
#endif

using namespace metal;

struct spvRayQueryMetadata { device const ulong* accelerationStructure; uint flags; };

intersection_params spvMakeIntersectionParams(uint flags)
{
    intersection_params ip;
    if ((flags & 1) != 0)
        ip.force_opacity(forced_opacity::opaque);
    if ((flags & 2) != 0)
        ip.force_opacity(forced_opacity::non_opaque);
    if ((flags & 4) != 0)
        ip.accept_any_intersection(true);
    if ((flags & 16) != 0)
        ip.set_triangle_cull_mode(triangle_cull_mode::back);
    if ((flags & 32) != 0)
        ip.set_triangle_cull_mode(triangle_cull_mode::front);
    if ((flags & 64) != 0)
        ip.set_opacity_cull_mode(opacity_cull_mode::opaque);
    if ((flags & 128) != 0)
        ip.set_opacity_cull_mode(opacity_cull_mode::non_opaque);
    if ((flags & 256) != 0)
        ip.set_geometry_cull_mode(geometry_cull_mode::triangle);
    if ((flags & 512) != 0)
        ip.set_geometry_cull_mode(geometry_cull_mode::bounding_box);
    return ip;
}

struct Output
{
    uint value;
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(1u);

struct spvDescriptorSetBuffer1
{
    device Output* outputData [[id(0)]];
};

struct spvDescriptorSetBuffer3
{
    device const ulong* scene [[id(0)]][1];
};

template<typename spvRTASArray13>
static inline __attribute__((always_inline))
device const ulong* getScene(spvRTASArray13 scenes, thread const uint& index)
{
    return scenes[index];
}

template<typename spvRTASArray18>
static inline __attribute__((always_inline))
uint trace(spvRTASArray18 scenes, thread raytracing::intersection_query<raytracing::instancing, raytracing::triangle_data>& query, thread spvRayQueryMetadata& _29_rayQueryMetadata)
{
    uint param = 0u;
    device const ulong* _32 = getScene(scenes, param);
    _29_rayQueryMetadata.accelerationStructure = _32;
    query.reset(ray(float3(0.0), float3(0.0, 0.0, -1.0), 0.0, 100.0), *(device const raytracing::acceleration_structure<raytracing::instancing>*)_32, 255u, spvMakeIntersectionParams(0u));
    bool _42 = query.next();
    if (_42)
    {
        uint _48 = ((device const uint*)_29_rayQueryMetadata.accelerationStructure[1])[query.get_candidate_instance_id()] & 0x00ffffffu;
        return _48;
    }
    return 0u;
}

kernel void main0(constant spvDescriptorSetBuffer1& spvDescriptorSet1 [[buffer(1)]], constant spvDescriptorSetBuffer3& spvDescriptorSet3 [[buffer(3)]])
{
    raytracing::intersection_query<raytracing::instancing, raytracing::triangle_data> query; spvRayQueryMetadata _29_rayQueryMetadata;
    uint _56 = trace(spvDescriptorSet3.scene, query, _29_rayQueryMetadata);
    (*spvDescriptorSet1.outputData).value = _56;
}

