#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>
#if __METAL_VERSION__ >= 230
#include <metal_raytracing>
using namespace metal::raytracing;
#endif

using namespace metal;

intersection_params spvMakeIntersectionParams(uint flags)
{
    intersection_params ip;
    if ((flags & 1) != 0)
        ip.force_opacity(forced_opacity::opaque);
    if ((flags & 2) != 0)
        ip.force_opacity(forced_opacity::non_opaque);
    if ((flags & 4) != 0)
        ip.accept_any_intersection(true);
    if ((flags & 16) != 0)
        ip.set_triangle_cull_mode(triangle_cull_mode::back);
    if ((flags & 32) != 0)
        ip.set_triangle_cull_mode(triangle_cull_mode::front);
    if ((flags & 64) != 0)
        ip.set_opacity_cull_mode(opacity_cull_mode::opaque);
    if ((flags & 128) != 0)
        ip.set_opacity_cull_mode(opacity_cull_mode::non_opaque);
    if ((flags & 256) != 0)
        ip.set_geometry_cull_mode(geometry_cull_mode::triangle);
    if ((flags & 512) != 0)
        ip.set_geometry_cull_mode(geometry_cull_mode::bounding_box);
    return ip;
}

struct Result
{
    float4 ray;
    float t;
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(1u);

kernel void main0(device Result& result [[buffer(0)]], raytracing::acceleration_structure<raytracing::instancing> scene [[buffer(1)]])
{
    float4 ray = result.ray;
    raytracing::intersection_query<raytracing::instancing, raytracing::triangle_data> query;
    query.reset(raytracing::ray(ray.xyz, float3(0.0, 0.0, 1.0), 0.0, ray.w), scene, 255u, spvMakeIntersectionParams(0u));
    for (;;)
    {
        bool _44 = query.next();
        if (_44)
        {
            query.commit_triangle_intersection();
            continue;
        }
        else
        {
            break;
        }
    }
    float _47 = query.get_committed_distance();
    result.t = _47;
}

