#include <metal_stdlib>
#include <simd/simd.h>
#if __METAL_VERSION__ >= 230
#include <metal_raytracing>
using namespace metal::raytracing;
#endif

using namespace metal;

struct spvDescriptorSetBuffer0
{
    texture2d<float, access::write> uImage [[id(0)]];
};

[[visible]] void main0(uint3 spvLaunchId, uint3 spvLaunchSize, SPV_RAY_CONTEXT_ARGS(void))
{
    const device spvDescriptorSetBuffer0& spvDescriptorSet0 = *reinterpret_cast<const device spvDescriptorSetBuffer0*>(spvRayState.dispatch->descriptorSetAddresses[0]);
    spvDescriptorSet0.uImage.write(float4(1.0), uint2(int2(spvLaunchId.xy)));
}

