#version 460
#extension GL_EXT_ray_query : require

layout(local_size_x = 1) in;
layout(set = 1, binding = 0, std430) buffer Output { uint value; } outputData;
layout(set = 3, binding = 5) uniform accelerationStructureEXT scene[1];
rayQueryEXT query;

accelerationStructureEXT getScene(accelerationStructureEXT scenes[1], uint index)
{
	return scenes[index];
}

uint trace(accelerationStructureEXT scenes[1])
{
	rayQueryInitializeEXT(query, getScene(scenes, 0), 0, 255, vec3(0), 0, vec3(0, 0, -1), 100);
	if (rayQueryProceedEXT(query))
		return rayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetEXT(query, false);
	return 0;
}

void main()
{
	outputData.value = trace(scene);
}
