#version 460
#extension GL_EXT_ray_query : require
layout(local_size_x = 1) in;

layout(set = 0, binding = 0) uniform accelerationStructureEXT scene;
layout(set = 0, binding = 1) buffer Result { vec4 ray; float t; } result;

void main()
{
	vec4 ray = result.ray;
	rayQueryEXT query;
	rayQueryInitializeEXT(query, scene, 0u, 0xffu, ray.xyz, 0.0, vec3(0.0, 0.0, 1.0), ray.w);
	while (rayQueryProceedEXT(query))
		rayQueryConfirmIntersectionEXT(query);
	result.t = rayQueryGetIntersectionTEXT(query, true);
}
